<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Click here</name>
   <tag></tag>
   <elementGuidId>82bb4ac7-4eac-45b8-bfb5-253f078d617e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='display_email']/div/div[2]/div/table/tbody/tr/td[2]/div/table/tbody/tr/td/p[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u1765956.ct.sendgrid.net/wf/click?upn=TwPuXU21FEh4rxDQqWxmZcnAzZl3K8nXVyPp8Aj59jrLJ9LVSC-2BM578BCGLMFytEILK11uqzvaHU7eM98EZ1dDIzx6jQzlIxEup0TI5DovAGc2-2Bz6aUtdymHXWvfRrCHbO5ANhJCrsZur2yUhuxzXxlSxd55C77vMNWA1L-2BGQ-2FGGOsroioGDrCRUI7KbnPYy_wnNHP-2Bs6UMFpXrgZLQQBgkZrgrD28Pi-2BhEf5UXA-2BhFLpZ3p0Ofb0gQkEDEE75vKKQrl9zTZniJWHsL4EzwUadA3lao1iRHVWe-2FSJiIm-2FlUKPkZrCRuty5rkFL-2FG5ZCkKHfweqaVcjdZDhNcqchF1k4tg6ozMH0YxazbD-2B9hbByQ-2F2i3xjZdeg880SbbJxy1orayUaew00AqzkWiZwA-2Fbqb-2FQJo2hXJv0QBZ5rc-2BPuqE-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click here</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;display_email&quot;)/div[@class=&quot;email_page&quot;]/div[@class=&quot;email&quot;]/div[@class=&quot;email_body&quot;]/table[1]/tbody[1]/tr[1]/td[2]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/p[3]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='display_email']/div/div[2]/div/table/tbody/tr/td[2]/div/table/tbody/tr/td/p[3]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <value>//a[contains(text(),'Click here')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jutlviui'])[2]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HERE'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <value>//a[contains(@href, 'https://u1765956.ct.sendgrid.net/wf/click?upn=TwPuXU21FEh4rxDQqWxmZcnAzZl3K8nXVyPp8Aj59jrLJ9LVSC-2BM578BCGLMFytEILK11uqzvaHU7eM98EZ1dDIzx6jQzlIxEup0TI5DovAGc2-2Bz6aUtdymHXWvfRrCHbO5ANhJCrsZur2yUhuxzXxlSxd55C77vMNWA1L-2BGQ-2FGGOsroioGDrCRUI7KbnPYy_wnNHP-2Bs6UMFpXrgZLQQBgkZrgrD28Pi-2BhEf5UXA-2BhFLpZ3p0Ofb0gQkEDEE75vKKQrl9zTZniJWHsL4EzwUadA3lao1iRHVWe-2FSJiIm-2FlUKPkZrCRuty5rkFL-2FG5ZCkKHfweqaVcjdZDhNcqchF1k4tg6ozMH0YxazbD-2B9hbByQ-2F2i3xjZdeg880SbbJxy1orayUaew00AqzkWiZwA-2Fbqb-2FQJo2hXJv0QBZ5rc-2BPuqE-3D')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//p[3]/a</value>
   </webElementXpaths>
</WebElementEntity>
